name: ci-pulls

on:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.org'

jobs:
  lint-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: nixbuild/nix-quick-install-action@v16
      with:
        nix_conf: experimental-features = nix-command flakes
    - uses: actions/checkout@v3
    - name: Check format
      run: nix run nixpkgs#nixfmt -- --check *.nix

  lint-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
